"""phase4 shop contact, category and product slugs

Revision ID: 1a3ac04d8277
Revises: e60ba903db97
Create Date: 2026-08-23 17:40:49.353486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a3ac04d8277'
down_revision: Union[str, None] = 'e60ba903db97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=160), nullable=True))
    op.execute("UPDATE categories SET slug = 'category-' || id WHERE slug IS NULL")
    op.alter_column('categories', 'slug', existing_type=sa.String(length=160), nullable=False)
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index('ix_categories_shop_id', 'categories', ['shop_id'], unique=False)
    op.create_unique_constraint('uq_categories_shop_slug', 'categories', ['shop_id', 'slug'])
    op.add_column('products', sa.Column('slug', sa.String(length=300), nullable=True))
    op.execute("UPDATE products SET slug = 'product-' || id WHERE slug IS NULL")
    op.alter_column('products', 'slug', existing_type=sa.String(length=300), nullable=False)
    op.create_index('ix_products_shop_id', 'products', ['shop_id'], unique=False)
    op.create_unique_constraint('uq_products_shop_slug', 'products', ['shop_id', 'slug'])
    op.add_column('shops', sa.Column('contact_phone', sa.String(length=32), nullable=True))
    op.add_column('shops', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('shops', sa.Column('address_line', sa.Text(), nullable=True))
    op.add_column('shops', sa.Column('city', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'city')
    op.drop_column('shops', 'address_line')
    op.drop_column('shops', 'contact_email')
    op.drop_column('shops', 'contact_phone')
    op.drop_constraint('uq_products_shop_slug', 'products', type_='unique')
    op.drop_index('ix_products_shop_id', table_name='products')
    op.drop_column('products', 'slug')
    op.drop_constraint('uq_categories_shop_slug', 'categories', type_='unique')
    op.drop_index('ix_categories_shop_id', table_name='categories')
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
