"""phase7 order snapshots and idempotency

Revision ID: cfe9746c9805
Revises: 1a3ac04d8277
Create Date: 2026-08-25 19:22:55.458162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cfe9746c9805'
down_revision: Union[str, None] = '1a3ac04d8277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('list_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute('UPDATE orders SET subtotal = total_amount WHERE subtotal IS NULL')
    op.alter_column(
        'orders', 'subtotal', existing_type=sa.Numeric(precision=12, scale=2), nullable=False
    )
    op.create_check_constraint('ck_orders_subtotal_non_negative', 'orders', 'subtotal >= 0')
    # Autogenerate cannot see new enum members, so the value is added explicitly.
    op.execute("ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PROCESSING'")
    op.add_column('orders', sa.Column('customer_name_snapshot', sa.String(length=256), nullable=True))
    op.add_column('orders', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index('ix_orders_customer_created', 'orders', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_orders_shop_status_created', 'orders', ['shop_id', 'status', 'created_at'], unique=False)
    op.create_unique_constraint('uq_orders_customer_idempotency', 'orders', ['customer_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_customer_idempotency', 'orders', type_='unique')
    op.drop_index('ix_orders_shop_status_created', table_name='orders')
    op.drop_index('ix_orders_customer_created', table_name='orders')
    op.drop_column('orders', 'idempotency_key')
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'customer_name_snapshot')
    op.drop_constraint('ck_orders_subtotal_non_negative', 'orders', type_='check')
    op.drop_column('orders', 'subtotal')
    op.drop_column('order_items', 'list_price_snapshot')
    # ### end Alembic commands ###
