"""phase3 auth identity sessions

Revision ID: e60ba903db97
Revises: cd2b06c51f13
Create Date: 2026-08-23 16:53:01.679300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e60ba903db97'
down_revision: Union[str, None] = 'cd2b06c51f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_auth_nonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('init_data_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('init_data_hash')
    )
    op.create_index('ix_telegram_auth_nonces_expires_at', 'telegram_auth_nonces', ['expires_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('principal_type', sa.Enum('CUSTOMER', 'SELLER', 'PLATFORM_ADMIN', name='principal_type'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform_admin_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_admin_id'], ['platform_admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.add_column('platform_admins', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('platform_admins', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('platform_admins', sa.Column('totp_secret', sa.Text(), nullable=True))
    op.add_column('platform_admins', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('platform_admins', sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('platform_admins', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('platform_admins', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("ALTER TYPE shop_member_role ADD VALUE IF NOT EXISTS 'ADMIN'")
    op.execute("DELETE FROM platform_admins WHERE email IS NULL")
    op.alter_column('platform_admins', 'email', nullable=False)
    op.alter_column('platform_admins', 'password_hash', nullable=False)
    op.alter_column('platform_admins', 'user_id', existing_type=sa.Integer(), nullable=True)
    op.execute('ALTER TABLE platform_admins DROP CONSTRAINT IF EXISTS platform_admins_user_id_fkey')
    op.create_foreign_key(
        'platform_admins_user_id_fkey', 'platform_admins', 'users',
        ['user_id'], ['id'], ondelete='SET NULL',
    )
    op.alter_column('platform_admins', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'platform_admins', ['email'])
    op.drop_constraint('platform_admins_user_id_fkey', 'platform_admins', type_='foreignkey')
    op.create_foreign_key(None, 'platform_admins', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE platform_admins DROP CONSTRAINT IF EXISTS platform_admins_user_id_fkey')
    op.execute("DELETE FROM platform_admins WHERE user_id IS NULL")
    op.alter_column('platform_admins', 'user_id', existing_type=sa.Integer(), nullable=False)
    op.create_foreign_key(
        'platform_admins_user_id_fkey', 'platform_admins', 'users',
        ['user_id'], ['id'], ondelete='CASCADE',
    )
    op.drop_constraint(None, 'platform_admins', type_='foreignkey')
    op.create_foreign_key('platform_admins_user_id_fkey', 'platform_admins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'platform_admins', type_='unique')
    op.alter_column('platform_admins', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('platform_admins', 'last_login_at')
    op.drop_column('platform_admins', 'locked_until')
    op.drop_column('platform_admins', 'failed_login_count')
    op.drop_column('platform_admins', 'is_active')
    op.drop_column('platform_admins', 'totp_secret')
    op.drop_column('platform_admins', 'password_hash')
    op.drop_column('platform_admins', 'email')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_telegram_auth_nonces_expires_at', table_name='telegram_auth_nonces')
    op.drop_table('telegram_auth_nonces')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS principal_type')
